import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/header";
import Provider from "./Components/Provider";
import Navbar from "./Components/navbar";
import Searchbox from "./Components/searchbox";

export const metadata = {
  title: "IMDb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Provider>
            <Header/>
            <Navbar/>
            <Searchbox/>
            {children}
        </Provider>
      </body>
    </html>
  );
}
